apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesproject
spec:
  selector:
    matchLabels:
      app: kubernetesproject
  replicas: 2
  template:
    metadata:
      labels:
        app: kubernetesproject
    spec:
      containers:
        - name: kubernetesproject
          image: thiambabel/kubernetesproject:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080